language: node_js
node_js:
- '10'

script: npx redoc-cli@0.9.11 bundle schema/agent.yml -o redoc/index.html

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN 
 local_dir: redoc
 keep_history: true
 on:
  branch: master
