openapi: 3.0.0
servers:
  - description: DINA - AAFC
    url: https://virtserver.dina-aafc.com/AAFC/1.0.0
info:
  description: Agent API Schema
  version: "1.0.0"
  title: Agent Schema
  contact:
    email: dina-aafc@canada.ca
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
   
paths:
  /v1/person:
    $ref: 'person.yml#/paths/~1v1~1person'
  /v1/person/{Id}:
    $ref: 'person.yml#/paths/~1v1~1person~1{Id}'  
  /v1/organization:
    $ref: 'organization.yml#/paths/~1v1~1organization'    
  /v1/organization/{Id}:
    $ref: 'organization.yml#/paths/~1v1~1organization~1{Id}'
